module.exports = {
    SKILLS: ['.NET',
        'Adobe Illustrator',
        'Amazon Kinesis',
        'Amazon Redshift',
        'Android',
        'Angular',
        'Animation',
        'Apache Kafka',
        'Apache Spark',
        'API Integrations- Dwolla',
        'API Integrations- Google Maps',
        'API Integrations- Layer',
        'API Integrations- Mixpanel',
        'API Integrations- Segment.io',
        'API Integrations- Facebook',
        'API Integrations- Stripe',
        'API Integrations- Twilio',
        'API Integrations- Voice Integrations (LEX)',
        'API Integrations- Branch.io',
        'API Integrations- Paypal',
        'API Integrations- GBG',
        'API Integrations- Equifax',
        'API Integrations- Onfido',
        'AR/VR',
        'AWS',
        'AWS Lambda',
        'Azure',
        'Backbone',
        'Brand Design',
        'Budget Management',
        'C',
        'C#',
        'C++',
        'Change Management',
        'Chrome Extension',
        'Firefox Extension',
        'Clojure',
        'Code Review',
        'Computer Vision',
        'Copywriting',
        'CSS',
        'Data Science',
        'DevOps',
        'Django',
        'Docker',
        'Drupal',
        'Elixir',
        'Ember',
        'Erlang',
        'Express',
        'Firebase',
        'Flutter',
        'Go',
        'Google Cloud Platform',
        'GraphQL',
        'Hadoop',
        'Haskell',
        'HTML',
        'Ideation',
        'Illustrations',
        'Information Architecture',
        'Interaction design',
        'Ionic',
        'iOS',
        'ISO',
        'Java',
        'Javascript',
        'Kly',
        'Kotlin',
        'Kubernetes',
        'Layer',
        'Logo and Icon design',
        'Loopback',
        'Machine Learning',
        'Marketing Design',
        'Meteor',
        'Mobile design',
        'MongoDB',
        'Motion design',
        'MySQL', 'Natural Language Processing',
        'NextJS',
        'Node',
        'NoSQL',
        'Objective-C',
        'OWASP',
        'PCI',
        'Pentest',
        'Perl',
        'Phonegap',
        'PHP',
        'Postgres',
        'Product Architecture',
        'Product Launch',
        'Product Management',
        'Program Management',
        'Project Management',
        'Python',
        'Quality Analyst',
        'R',
        'Rails',
        'React',
        'Test Automation',
        'React Native',
        'Redux',
        'Release Management',
        'RethinkDB',
        'Roadmap Definition',
        'Ruby',
        'Scala',
        'Scikit-Learn',
        'Scoping',
        'Security',
        'Shopify',
        'Sketch',
        'Socket.io',
        'SOCs',
        'Spring',
        'SQL',
        'Swift',
        'Team Management',
        'Technical Architecture',
        'Training',
        'Typescript',
        'Typography',
        'UI',
        'Usability testing',
        'User Research',
        'UX',
        'Visual Design',
        'Vulnerability Scanning',
        'Web design',
        'Webpack',
        'Wordpress',
        'Xamarin',
        'Jira',
        'Terraform',
        'OPA',
        'Stackdriver',
        'Splunk',
        'Jenkins',
        'SAP Hybris',
        'MuleSoft',
        'CRM development',
        'ESB',
        'Microsoft Dynamics 365',
        'Workday',
        'Oracle',
        'Oracle Netsuite',
        'SAP S/4HANA',
        'Nexidia',
        'Calabrio',
        'Callminer',
        'Aspect',
        'Robotic Process Automation',
        'UIPath'
    ]
};
